DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
    customer_id INTEGER,
    age INTEGER,
    gender TEXT,
    item_purchased TEXT,
    category TEXT,
    purchased_amount NUMERIC,
    location TEXT,
    size TEXT,
    color TEXT,
    season TEXT,
    review_rating NUMERIC,
    subscription_status TEXT,
    shipping_type TEXT,
    discount_applied TEXT,
    previous_purchases INTEGER,
    payment_method TEXT,
    frequency_of_purchases TEXT,
    age_group TEXT,
    purchase_frequency_days INTEGER
);

SELECT COUNT(*) FROM customer;
SELECT * FROM customer LIMIT 5;


--Q1. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchased_amount 
from customer 
where discount_applied = 'Yes' and purchased_amount >= (select AVG(purchased_amount) from customer)

-- Q2. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q3. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchased_amount) as revenue
from customer
group by gender

--Q4. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q5. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchased_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q6. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchased_amount),2) AS avg_spend,
       ROUND(SUM(purchased_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q7. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchased_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q9. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q10. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q11 Which categories drive the MOST revenue but have LOW review ratings?
SELECT category,
       ROUND(SUM(purchased_amount),2) AS total_revenue,
       ROUND(AVG(review_rating),2) AS avg_rating
FROM customer
GROUP BY category
HAVING AVG(review_rating) < 3.5
ORDER BY total_revenue DESC;

-- Q12 Which payment methods are associated with higher spending?
SELECT payment_method,
       ROUND(AVG(purchased_amount),2) AS avg_spend,
       ROUND(SUM(purchased_amount),2) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY avg_spend DESC;

--Q13 Do discounts increase purchase frequency or just reduce margin?
SELECT discount_applied,
       ROUND(AVG(previous_purchases),2) AS avg_previous_purchases,
       ROUND(AVG(purchased_amount),2) AS avg_spend
FROM customer
GROUP BY discount_applied;

--Q 14 Which customer segments generate the highest revenue?
WITH segments AS (
    SELECT customer_id,
           purchased_amount,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS segment
    FROM customer
)
SELECT segment,
       COUNT(customer_id) AS customers,
       ROUND(SUM(purchased_amount),2) AS total_revenue,
       ROUND(AVG(purchased_amount),2) AS avg_spend
FROM segments
GROUP BY segment
ORDER BY total_revenue DESC;

--Q15 Which locations generate high revenue but low subscription adoption?
SELECT location,
       ROUND(SUM(purchased_amount),2) AS total_revenue,
       COUNT(*) FILTER (WHERE subscription_status = 'Yes') AS subscribers,
       COUNT(*) AS total_customers
FROM customer
GROUP BY location
HAVING COUNT(*) FILTER (WHERE subscription_status = 'Yes') < COUNT(*) * 0.3
ORDER BY total_revenue DESC;

--Q16 Are express shipping customers more satisfied?
SELECT shipping_type,
       ROUND(AVG(review_rating),2) AS avg_rating,
       ROUND(AVG(purchased_amount),2) AS avg_spend
FROM customer
GROUP BY shipping_type;

--Q17 What % of revenue comes from loyal customers?
WITH segments AS (
    SELECT purchased_amount,
           CASE 
               WHEN previous_purchases > 10 THEN 'Loyal'
               ELSE 'Other'
           END AS segment
    FROM customer
)
SELECT segment,
       ROUND(100.0 * SUM(purchased_amount) /
       (SELECT SUM(purchased_amount) FROM customer),2) AS revenue_percentage
FROM segments
GROUP BY segment;

